language: ruby
cache: bundler
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --file-ignore "/_site\/assets/"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
    apt:
        packages:
            - sshpass
env:
    global:
        # $DEPLOY_PATH
        - secure: "Te7AgRPr0ZSDtbqD3Jt538GZ++/DJOnUtMrmfFHAxwKvueXsDryxL+ch0NNFZrMC3vLNZAS1Z5y1vLmmIIJmp+hgciLGOziH917wfAOSFq5rI/YDoXwsfWiYqMed6UMlL5aixWdEQvXckiom2PboRR7NmrBbEELlNzWXA10zEl4j656ani1+HTH1d46D6/eBKTxUyfFIw4/QPY6vy61zzVIo0eakYQY6hr1tgLSYCQl7ZtX2HTqbDCIVNk1X5qQ6SAUkSdvlyAlcYkAV8jGsZQrQvNrAZu2q0KTgY6iSr2Js25TL4DJTjdJcJ2ehbMYDj6oW2Bc3X/pGIVMNpp2qL5i/JvbGzP2bx3xHxMujXEz6lw9G7YOXbnhMWI0hYLjFK9uqTgcEeR9Fn1RoztuvWd8jIf40uDs2dtgEdsNf3PxNqTrpMbVMFIlQvmZArXZJtYnfFY/feA3bROJ37pRu7Lo4pw5Npel909QUPzXzpiqho8WK7BwnYxzNWl5vtf9wvtOAtoDmUurhgDGn/fdiSPGVk/FvXMJkdOzMiT6bKNPB9miARteka9n9mrdeG5cs0xukglUOCCT8ObqAyoZzM2iQSbWUAukN3ejUxekMxnaYT6iHwOSlWz/1aiOLl4jGaOIdSAGAAgQDYche1s7/go+zPBiZgTyJDJBLp62GDQY="        
        # $DEPLOY_USER
        - secure: "TicuNHpwNXg1Ibd46Ku4XdrLeA3Jr7NBcudLOlE5RfWQlLZXzcGAJsIiGXLIrO9CVewa/WkRV0w1n8YdVW+8/ELwsMJorstvMu3LgzFJWUxmr/6BZI3dcwijVw0UxamPsTWBA2DqRyjPCTiUY6Kuf8tFAQU86wUT0ZfY76pZBsNla4rYCEnoSI0fjB/SHaa4EFOy8l7lEz+RvaWueXkSgzXwqO+Zf3H3/3zi5CrAbRVdBYkDH9+sapZCsJpFh8jEYPQ4bJXr0Hv4zsB+A/LLoc/C4Svxa3D0SPzxA6rWjCEI9A3el74/mNxTKQegGx5RiStKHSxKED0a/9rG4PGpsrVvJcUbxD8NMEZcOATPz1shaMvTn9K73OgLf3NQEIXA2Ekoy3Esusmqz+MhoIIepA4KMOQrp/wvJknXD+REko2zmZDraV2kbN4RauRhRj/S3ABQXxvxtuIoZo/7zm5Yoy5rnyFZrZlNg/z87nve24KEJnPcPIzJESzlxeJ1mSSfSmk4XNtnUqivK8b6ZyMLf7KcFjBmX90TkONfo03RtGyqH7UQSfHriLRiYiZZoFOD+zWqo5gjvnr61ZJhRNX9yTfjB69RlHFURP3gT8HNxbbrF2oXgqcNVylpKZk/ocORggWuTZwRJFzy5sQYXtpVrJXYyDAOkXSsCBT0MXeFA3c="
        # $DEPLOY_PASS
        - secure: "gglJTl8gG9YPsHtxstBRfgbruxBRFvYPvh5qshIY79ogxtQgTSCzg9bkAQRxubTyzszazebzHubVhunWvIFfjJ6WFIcZDna18kJMV4H4bxMgxhXZoQrjF5MWiWvGYMuInxeb6ZFu8DyF/yry+R8OXQSpu10bhJyjQxd+ksdK7FLnRbymOpIdyzfdqF1g/5XwVlFgW/RAPtxBwXc/629OX/CMSJIy1SLMSjOWuJBHJLrouuKqRZhCyg2LqcVvo09W6lJY/elhy0AgEj0cfmvRZyWlbb08YCMHzUgPrSN+PiKRIGlyEq/5QL2gHOZ8RUGdWjwXKVsavxjn264ub9l9kCAVKfDTYKDqgdXOWXeXkwGoiCMPH0rM+URVesNLbhJaMzANRGdNhBB8Ln8j260Ja5wMI4Fon+asrA3AnVi9m97Lj04wotatzQExgbS7QMVplGvPjig0KxXKDMPXqRXURlmMVA0+gAVmxe88P4dnjKnOOhwN40m+Kgx5xpG4BQXLqRSABC+m8t4vBMkwiPBBwAWUr4/ougiPdYz+zhsIVJJNiJBAKxmBaxx4QL0hZxOMSKf6RNoz+Bhc5rRhR62q/D0bjlU6NsHe34NCiK7HnaLNTFNXz2tzZjrcuZSXWMzFzvMZc8M7+vyPnxUwpiUyDjr5Qq5PhmLzFmFL0pzvgPg="
        # $DEPLOY_HOST
        - secure: "QkEihRXbMF7txrCSnzBc525jzGdiV2aY1auVSeN14sOyimEb8WLDLcEBB3WPds1lg3jEBUDamI/tviuYnLGTv4rnYag8QxeqEsX7XuXvrapoee5Qa5WLq3OvR6rrJER5dEObOiHUMm/8SqR0THFvC8C93RHnHOlNQ6whD//lVZL/Phtl24nin0U7Bnus0+WSeVVPhbwf//BBkvVK6kp2PfTpw4vDG1HiqU1RNQ6J/V7Y7rpeOmrZWLfwoDzMbs1D3jK1slVL7JB1TcS0x0uELz+4DMcS/40MheHcFCg9emf49H6Q64PtshfxhNKwTY33ZdYiWLARROvdHdCuPzbi+PYmulXp2eWlmKM5lKZjiPgwvtZ95meV9hQuJyk7MN+2pyrHx/+VzeCsaN+M9wi8ARlGpW5XeZAC61ChsDgcDhjMxVRo3Y5BUZTIbdcnUAVKoAx0qeCosvO0hWErerG0+v2Mo678hatVAuga2bx17eJMU87nA7pKFqay0gsXfQZjU9RZZzNzDWLLKPLTKqfgKPDGVuAfKmt0mC6GvDsANKXZzCAR9odXVfZCJz7AZKZR5BFhl2JlpnrtxHWsMdTsbOgy/OSifZzrDWhWO4u9qFhOzmbdY9z+4iiv3StaHU8o4dPflKxRDuzPz+50v0dM1JnZjY6ek2CBbLPDh2aK4SE="

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./travis-deploy.sh
